# Generated by Django 4.2.2 on 2023-06-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_persona_responsable_ubicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona_responsable',
            old_name='edad',
            new_name='edad_persona',
        ),
    ]
